### ISSUE TITLE
API: issue tracking

### ISSUE THREAD

**Issue by dvbmgr** [publica-re/api.publica.re#3]
- [ ] specify issue structure
- [ ] handle link with repositories
- [ ] handle event detection
- [ ] handle spam notifications
- [ ] handle links with other issues and merge requests
